"""
Google Gemini API helpers (server-side only). Requires GEMINI_API_KEY in settings.
"""

from __future__ import annotations

import json
import logging
from collections.abc import Iterator
from typing import Any

from django.conf import settings

logger = logging.getLogger(__name__)

ASSISTANT_SYSTEM = (
    "You are a helpful assistant in a chat app. Answer clearly and directly, like a concise "
    "search-style summary when the user asks for facts or explanations. If you are unsure, say so. "
    "Refuse only requests that are clearly illegal or intended to cause serious harm; otherwise "
    "be helpful. Keep answers focused; use short paragraphs or bullet points when appropriate."
)

TRANSCRIPT_SYSTEM = (
    "You output only valid JSON when asked. No markdown fences, no commentary before or after."
)

CODE_PROJECT_SYSTEM = (
    "You output only valid JSON. No markdown fences, no commentary before or after the JSON.\n"
    "The user downloads these files individually and as a ZIP in the app: you MUST fill the files array "
    "with complete path + content for every file. Never return an empty files array. "
    "For anything described as a project, app, site, or API, include at least 2 files (code + README or similar)."
)

CODEGEN_COACH_DISCOVER = (
    "You help with software in a chat app. The user wants code generated by the app (ZIP)—not a long interview.\n"
    "Do NOT ask which technology, framework, database, scale, or stack to use—infer defaults from their message.\n"
    "Do NOT ask clarifying questions unless the request is empty; if vague, state assumptions briefly.\n"
    "Reply in 1–3 short sentences. Downloadable files (preview + ZIP) come from the app’s Generate code action.\n"
    "End every reply with a new line containing exactly: [[READY_TO_GENERATE]]\n"
)

CODEGEN_COACH_REFINE = (
    "The user already has generated project files. Continue: answer questions, suggest changes, stay concise. "
    "Avoid huge code dumps. Tell them to use “Update project from chat” to regenerate files.\n"
    "If regeneration is the right next step, end with: [[READY_TO_UPDATE]]\n"
)

CODEGEN_COACH_CODE_IN_REPLY_SUFFIX = (
    "\nYou MAY include code in your replies: use markdown code fences (```language). "
    "For a whole file, put a line immediately before the fence like: **File: path/to/file.ext** "
    "then the fenced code. For tiny examples, a single short fence is enough. "
    "Never output raw JSON meant for ZIP download here.\n"
)

CODEGEN_COACH_REFINE_CODE_SUFFIX = (
    "\nYou MAY include fenced code (**File: path** + block, or short snippets) when it helps. "
    "Use [[READY_TO_UPDATE]] when a full regeneration is best.\n"
)

def is_configured() -> bool:
    key = getattr(settings, "GEMINI_API_KEY", "") or ""
    return bool(key.strip())


# Ordered fallbacks when the configured model is missing (404) — e.g. deprecated 2.0 Flash.
_MODEL_FALLBACKS = (
    "gemini-2.5-flash",
    "gemini-2.5-flash-lite",
    "gemini-1.5-flash",
)


def _model_candidates() -> list[str]:
    configured = (getattr(settings, "GEMINI_MODEL", "") or "").strip()
    primary = configured or "gemini-2.5-flash"
    out: list[str] = []
    for m in (primary,) + _MODEL_FALLBACKS:
        if m and m not in out:
            out.append(m)
    return out


def _is_model_not_found(exc: Exception) -> bool:
    msg = str(exc).lower()
    return (
        "404" in msg
        or "not found" in msg
        or "invalid model" in msg
        or "does not exist" in msg
        or "is not found" in msg
    )


def _ensure_genai():
    try:
        import google.generativeai as genai
    except ImportError:
        return None, "The google-generativeai package is not installed."

    key = (getattr(settings, "GEMINI_API_KEY", "") or "").strip()
    if not key:
        return None, "AI is not configured (missing GEMINI_API_KEY)."
    genai.configure(api_key=key)
    return genai, None


def assistant_reply(
    history: list[dict[str, Any]],
    user_message: str,
) -> tuple[str | None, str | None]:
    """
    Multi-turn assistant. history items: {"role": "user"|"model", "text": "..."}.
    Returns (assistant_text, error_message).
    """
    text = (user_message or "").strip()
    if not text:
        return None, "Message is empty."
    if len(text) > 8000:
        return None, "Message is too long."

    genai_mod, err = _ensure_genai()
    if err:
        return None, err

    hist: list[dict[str, Any]] = []
    for m in (history or [])[-24:]:
        role = m.get("role")
        part = (m.get("text") or "").strip()
        if not part or role not in ("user", "model"):
            continue
        r = "user" if role == "user" else "model"
        hist.append({"role": r, "parts": [part[:8000]]})

    last_missing: Exception | None = None
    for model_name in _model_candidates():
        model = genai_mod.GenerativeModel(model_name, system_instruction=ASSISTANT_SYSTEM)
        try:
            chat = model.start_chat(history=hist)
            resp = chat.send_message(text)
            out = (resp.text or "").strip()
            if not out:
                return None, "The model returned an empty response. Try rephrasing."
            return out, None
        except Exception as e:
            if _is_model_not_found(e):
                last_missing = e
                logger.warning("Gemini model %r unavailable (%s); trying fallback", model_name, e)
                continue
            logger.exception("Gemini assistant_reply failed")
            return None, _friendly_api_error(e)
    return None, _friendly_api_error(last_missing) if last_missing else "No Gemini model available."


def stream_codegen_coach(
    messages: list[dict[str, Any]],
    phase: str = "discover",
    include_code: bool = True,
) -> Iterator[str]:
    genai_mod, err = _ensure_genai()
    if err:
        raise RuntimeError(err)

    ph = (phase or "").lower()
    if not include_code:
        sys_inst = ASSISTANT_SYSTEM
    elif ph == "refine":
        sys_inst = CODEGEN_COACH_REFINE + CODEGEN_COACH_REFINE_CODE_SUFFIX
    else:
        sys_inst = CODEGEN_COACH_DISCOVER + CODEGEN_COACH_CODE_IN_REPLY_SUFFIX
    clean: list[dict[str, str]] = []
    for m in (messages or [])[-40:]:
        r = m.get("role")
        c = (m.get("content") or "").strip()
        if not c or r not in ("user", "assistant"):
            continue
        clean.append({"role": r, "content": c[:14000]})
    if not clean or clean[-1]["role"] != "user":
        raise RuntimeError("Last message must be from the user.")

    hist: list[dict[str, Any]] = []
    for m in clean[:-1]:
        rr = "user" if m["role"] == "user" else "model"
        hist.append({"role": rr, "parts": [m["content"]]})
    last_user = clean[-1]["content"]

    last_missing: Exception | None = None
    for model_name in _model_candidates():
        model = genai_mod.GenerativeModel(model_name, system_instruction=sys_inst)
        try:
            chat = model.start_chat(history=hist)
            for chunk in chat.send_message(last_user, stream=True):
                t = getattr(chunk, "text", None) or ""
                if t:
                    yield t
            return
        except Exception as e:
            if _is_model_not_found(e):
                last_missing = e
                logger.warning("Gemini model %r unavailable for stream (%s)", model_name, e)
                continue
            logger.exception("Gemini stream_codegen_coach failed")
            raise RuntimeError(_friendly_api_error(e)) from e
    raise RuntimeError(_friendly_api_error(last_missing) if last_missing else "No Gemini model available.")


def generate_code_project(
    user_prompt: str,
    stack_hint: str = "",
    continuation_note: str | None = None,
) -> tuple[dict[str, Any] | None, str | None]:
    prompt = (user_prompt or "").strip()
    if not prompt:
        return None, "Describe what you want to build."
    if len(prompt) > 24000:
        return None, "Request is too long (max 24000 characters)."

    stack = (stack_hint or "").strip()[:120]
    genai_mod, err = _ensure_genai()
    if err:
        return None, err

    extra = ""
    if continuation_note and continuation_note.strip():
        extra = f"\n\nAdditional instruction:\n{continuation_note.strip()[:4000]}"

    spec = f"""Build downloadable source files the user will preview in the app and download as one ZIP.

Full specification (constraints and features — respect all of it):
{prompt}

Tech / language hint (may be empty — pick a sensible stack if so): {stack or "auto"}
{extra}

Return a single JSON object with exactly these keys:
- "project_name": short slug, lowercase letters digits and hyphens only, max 40 characters
- "summary": one sentence describing what you generated
- "files": array of 1 to 14 objects, each with "path" (relative path, forward slashes, no ".." segments) and "content" (complete UTF-8 file body as a string)

Mandatory:
- The files array MUST NOT be empty. Each file must have full content (not empty unless the file is intentionally empty).
- For a project, app, site, or API: at least 2 files (e.g. code + README.md).
- For a single script: one file with a clear path.

Rules:
- Prefer real, runnable code over placeholders like TODO unless unavoidable.
- Include README.md for multi-file projects.
- Text files only. No binary.
- Keep each file under 12000 characters; prefer fewer complete files if needed.
- Output valid JSON only."""

    last_missing: Exception | None = None
    for model_name in _model_candidates():
        model = genai_mod.GenerativeModel(model_name, system_instruction=CODE_PROJECT_SYSTEM)
        raw = ""
        try:
            resp = model.generate_content(
                spec,
                generation_config=genai_mod.GenerationConfig(
                    response_mime_type="application/json",
                ),
            )
            raw = (resp.text or "").strip()
            data = json.loads(raw)
            if not isinstance(data, dict):
                return None, "Invalid AI response format."
            pn = str(data.get("project_name", "")).strip()
            summary = str(data.get("summary", "")).strip()
            files = data.get("files")
            if not isinstance(files, list) or len(files) < 1:
                return None, "The model did not return usable files. Try again with more detail."
            out_files: list[dict[str, str]] = []
            for item in files:
                if not isinstance(item, dict):
                    continue
                path = str(item.get("path", "")).strip().lstrip("/")
                content = str(item.get("content", ""))
                if path:
                    out_files.append({"path": path, "content": content})
            if len(out_files) < 1:
                return None, "No valid files in the AI response. Try again."
            return {
                "project_name": pn or "generated-project",
                "summary": summary[:500],
                "files": out_files,
            }, None
        except json.JSONDecodeError:
            logger.warning("Gemini code project JSON parse failed: %s", raw[:500] if raw else "")
            if len(raw) > 200:
                return None, "OUTPUT_TRUNCATED"
            return None, "Could not parse AI response. Try again."
        except Exception as e:
            if _is_model_not_found(e):
                last_missing = e
                logger.warning("Gemini model %r unavailable (%s); trying fallback", model_name, e)
                continue
            logger.exception("Gemini generate_code_project failed")
            return None, _friendly_api_error(e)
    return None, _friendly_api_error(last_missing) if last_missing else "No Gemini model available."


def generate_transcript_json(
    scenario: str,
    room_summary: str,
    num_turns: int,
) -> tuple[list[dict[str, str]] | None, str | None]:
    """Returns list of {"side": "me"|"other", "text": "..."} or error."""
    scenario = (scenario or "").strip()
    if not scenario:
        return None, "Describe what conversation you want."
    if len(scenario) > 4000:
        return None, "Scenario is too long."

    n = max(4, min(int(num_turns or 8), 24))

    genai_mod, err = _ensure_genai()
    if err:
        return None, err

    ctx = (room_summary or "").strip()[:2000]
    prompt = f"""Create a fictional chat transcript for a messaging app.

Context about the chat (may be empty): {ctx}

User request: {scenario}

Return a JSON array of {n} messages alternating speakers. Each item must be an object with:
- "side": either "me" (the user who requested this) or "other" (the other participant)
- "text": the message text (natural, casual chat; each under 400 characters)

Start with "me" or "other" as appropriate. Output ONLY the JSON array, no markdown."""

    raw = ""
    last_missing: Exception | None = None
    for model_name in _model_candidates():
        model = genai_mod.GenerativeModel(model_name, system_instruction=TRANSCRIPT_SYSTEM)
        try:
            resp = model.generate_content(
                prompt,
                generation_config=genai_mod.GenerationConfig(
                    response_mime_type="application/json",
                ),
            )
            raw = (resp.text or "").strip()
            data = json.loads(raw)
            if not isinstance(data, list):
                return None, "Invalid AI response format."
            cleaned: list[dict[str, str]] = []
            for item in data:
                if not isinstance(item, dict):
                    continue
                side = str(item.get("side", "")).lower()
                t = str(item.get("text", "")).strip()
                if side not in ("me", "other") or not t:
                    continue
                cleaned.append({"side": side, "text": t[:2000]})
            if len(cleaned) < 2:
                return None, "Could not parse a usable transcript. Try again with a clearer prompt."
            return cleaned, None
        except json.JSONDecodeError:
            logger.warning("Gemini transcript JSON parse failed: %s", raw[:500])
            return None, "Could not parse AI response. Try again."
        except Exception as e:
            if _is_model_not_found(e):
                last_missing = e
                logger.warning("Gemini model %r unavailable (%s); trying fallback", model_name, e)
                continue
            logger.exception("Gemini generate_transcript_json failed")
            return None, _friendly_api_error(e)
    return None, _friendly_api_error(last_missing) if last_missing else "No Gemini model available."


def _friendly_api_error(e: Exception) -> str:
    msg = str(e).lower()
    if "api key" in msg or "401" in msg or "403" in msg:
        return "AI key is invalid or not allowed for this model. Check GEMINI_API_KEY and GEMINI_MODEL."
    if "429" in msg or "resource exhausted" in msg:
        return "AI quota exceeded. Try again later."
    if "404" in msg or "not found" in msg:
        return (
            "That Gemini model is not available for your API key (often deprecated). "
            "Set GEMINI_MODEL to gemini-2.5-flash or gemini-1.5-flash in your environment."
        )
    return "AI request failed. Please try again in a moment."


def summarize_recent_messages(lines: list[str]) -> tuple[str | None, str | None]:
    """Optional: compact summary of last messages for context."""
    if not lines:
        return None, "No messages to summarize."
    genai_mod, err = _ensure_genai()
    if err:
        return None, err

    blob = "\n".join(lines[-40:])[:12000]
    summary_prompt = (
        "Summarize this chat history in 3–6 short bullet points for the user. "
        "Focus on decisions, open questions, and tone.\n\n---\n" + blob
    )
    last_missing: Exception | None = None
    for model_name in _model_candidates():
        model = genai_mod.GenerativeModel(model_name)
        try:
            resp = model.generate_content(summary_prompt)
            out = (resp.text or "").strip()
            return (out, None) if out else (None, "Empty summary.")
        except Exception as e:
            if _is_model_not_found(e):
                last_missing = e
                logger.warning("Gemini model %r unavailable (%s); trying fallback", model_name, e)
                continue
            logger.exception("Gemini summarize failed")
            return None, _friendly_api_error(e)
    return None, _friendly_api_error(last_missing) if last_missing else "No Gemini model available."
