"""
Groq API helpers (server-side only). Requires GROQ_API_KEY in settings.
Groq hosts fast LLM inference (Llama, Mixtral, etc.) at api.groq.com.
Mirrors the interface of gemini_client.py so ai_service.py can swap providers.

Install: pip install groq
Get key: https://console.groq.com
"""

from __future__ import annotations

import json
import logging
from collections.abc import Iterator
from typing import Any

from django.conf import settings

logger = logging.getLogger(__name__)

ASSISTANT_SYSTEM = (
    "You are a helpful assistant in a chat app. Answer clearly and directly, like a concise "
    "search-style summary when the user asks for facts or explanations. If you are unsure, say so. "
    "Refuse only requests that are clearly illegal or intended to cause serious harm; otherwise "
    "be helpful. Keep answers focused; use short paragraphs or bullet points when appropriate."
)

TRANSCRIPT_SYSTEM = (
    "You output only valid JSON when asked. No markdown fences, no commentary before or after."
)

CODE_PROJECT_SYSTEM = (
    "You output only valid JSON. No markdown code fences, no commentary before or after the JSON.\n"
    "The user downloads these files individually and as a ZIP in the app: you MUST fill the files array "
    "with complete path + content for every file. Never return an empty files array. "
    "For anything described as a project, app, site, or API, include at least 2 files (code + README or similar)."
)

CODEGEN_COACH_DISCOVER = (
    "You help with software in a chat app. The user wants code generated by the app (ZIP)—not a long interview.\n"
    "Rules:\n"
    "- Do NOT ask which technology, framework, database, scale, or deployment stack to use. "
    "Infer sensible defaults from what they already said.\n"
    "- Do NOT ask clarifying questions unless the request is empty or impossible to interpret; if vague, "
    "state your assumptions in one short sentence instead of asking.\n"
    "- Keep replies brief (1–3 short sentences). Real downloadable files (preview + ZIP) come from the app’s "
    "Generate code button—not from pasting binaries in chat.\n"
    "- End every reply with a new line containing exactly: [[READY_TO_GENERATE]]\n"
)

CODEGEN_COACH_REFINE = (
    "The user already generated a downloadable code project in this tool. Continue the conversation: answer "
    "questions, suggest improvements, and discuss changes. Keep replies concise. Do not paste huge multi-file "
    "code dumps—short snippets only when needed. If they want the files regenerated from this chat, tell them "
    "to use the “Update project from chat” button.\n"
    "If you believe the next step is to regenerate all project files from the conversation, end with a line "
    "containing exactly: [[READY_TO_UPDATE]]\n"
)

# Shown after CODEGEN_COACH_* when the user opted into code in replies (markdown fences, optional file labels).
CODEGEN_COACH_CODE_IN_REPLY_SUFFIX = (
    "\nYou MAY include code in your replies: use markdown code fences (```language). "
    "For a whole file, put a line immediately before the fence like: **File: path/to/file.ext** "
    "then the fenced code. For tiny examples, a single short fence is enough—no file label needed. "
    "Never output raw JSON meant for ZIP download here; the app generates the bundle separately.\n"
)

CODEGEN_COACH_REFINE_CODE_SUFFIX = (
    "\nYou MAY include fenced code (**File: path** + block, or short snippets) when it helps. "
    "Avoid dumping entire projects in chat; use [[READY_TO_UPDATE]] when a full regeneration is best.\n"
)

# Model fallback chain — Groq-hosted models
_MODEL_FALLBACKS = (
    "llama-3.3-70b-versatile",
    "llama-3.1-70b-versatile",
    "llama3-70b-8192",
    "mixtral-8x7b-32768",
)


def is_configured() -> bool:
    key = getattr(settings, "GROQ_API_KEY", "") or ""
    return bool(key.strip())


def _get_client():
    try:
        from groq import Groq
    except ImportError:
        return None, "The groq package is not installed. Run: pip install groq"

    key = (getattr(settings, "GROQ_API_KEY", "") or "").strip()
    if not key:
        return None, "Groq AI is not configured (missing GROQ_API_KEY)."

    client = Groq(api_key=key)
    return client, None


def _model_candidates() -> list[str]:
    configured = (getattr(settings, "GROQ_MODEL", "") or "").strip()
    primary = configured or "llama-3.3-70b-versatile"
    out: list[str] = []
    for m in (primary,) + _MODEL_FALLBACKS:
        if m and m not in out:
            out.append(m)
    return out


def _is_model_not_found(exc: Exception) -> bool:
    msg = str(exc).lower()
    return (
        "404" in msg
        or "not found" in msg
        or "invalid model" in msg
        or "does not exist" in msg
        or "model_not_found" in msg
        or "decommissioned" in msg
    )


def assistant_reply(
    history: list[dict[str, Any]],
    user_message: str,
) -> tuple[str | None, str | None]:
    """
    Multi-turn assistant using Groq.
    history items: {"role": "user"|"model", "text": "..."}.
    Returns (assistant_text, error_message).
    """
    text = (user_message or "").strip()
    if not text:
        return None, "Message is empty."
    if len(text) > 8000:
        return None, "Message is too long."

    client, err = _get_client()
    if err:
        return None, err

    # Build messages in OpenAI-compatible format
    messages = [{"role": "system", "content": ASSISTANT_SYSTEM}]
    for m in (history or [])[-24:]:
        role = m.get("role")
        part = (m.get("text") or "").strip()
        if not part or role not in ("user", "model"):
            continue
        # Gemini uses "model", OpenAI/Groq uses "assistant"
        oai_role = "user" if role == "user" else "assistant"
        messages.append({"role": oai_role, "content": part[:8000]})
    messages.append({"role": "user", "content": text})

    last_err: Exception | None = None
    for model_name in _model_candidates():
        try:
            resp = client.chat.completions.create(
                model=model_name,
                messages=messages,
                temperature=1,
                max_completion_tokens=2048,
                top_p=1,
                stream=False,
                stop=None,
            )
            out = (resp.choices[0].message.content or "").strip()
            if not out:
                return None, "The model returned an empty response. Try rephrasing."
            return out, None
        except Exception as e:
            if _is_model_not_found(e):
                last_err = e
                logger.warning("Groq model %r unavailable (%s); trying fallback", model_name, e)
                continue
            logger.exception("Groq assistant_reply failed — model=%s error=%s", model_name, e)
            return None, _friendly_api_error(e)

    return None, _friendly_api_error(last_err) if last_err else "No Groq model available."


def stream_codegen_coach(
    messages: list[dict[str, Any]],
    phase: str = "discover",
    include_code: bool = True,
) -> Iterator[str]:
    """Stream assistant tokens: project coach (include_code) or general chat (not include_code)."""
    client, err = _get_client()
    if err:
        raise RuntimeError(err)

    ph = (phase or "").lower()
    if not include_code:
        sys_msg = ASSISTANT_SYSTEM
    elif ph == "refine":
        sys_msg = CODEGEN_COACH_REFINE + CODEGEN_COACH_REFINE_CODE_SUFFIX
    else:
        sys_msg = CODEGEN_COACH_DISCOVER + CODEGEN_COACH_CODE_IN_REPLY_SUFFIX
    oai: list[dict[str, Any]] = [{"role": "system", "content": sys_msg}]
    for m in (messages or [])[-40:]:
        role = m.get("role")
        c = (m.get("content") or "").strip()
        if not c or role not in ("user", "assistant"):
            continue
        oai.append({"role": role, "content": c[:14000]})
    if len(oai) < 2:
        raise RuntimeError("Send at least one user message.")

    last_err: Exception | None = None
    for model_name in _model_candidates():
        try:
            stream = client.chat.completions.create(
                model=model_name,
                messages=oai,
                temperature=0.55,
                max_completion_tokens=4096,
                top_p=1,
                stream=True,
            )
            for chunk in stream:
                ch0 = chunk.choices[0]
                delta = getattr(ch0, "delta", None)
                if delta and getattr(delta, "content", None):
                    yield delta.content
            return
        except Exception as e:
            if _is_model_not_found(e):
                last_err = e
                logger.warning("Groq model %r unavailable for stream (%s); trying fallback", model_name, e)
                continue
            logger.exception("Groq stream_codegen_coach failed — model=%s", model_name)
            raise RuntimeError(_friendly_api_error(e)) from e

    raise RuntimeError(_friendly_api_error(last_err) if last_err else "No Groq model available.")


def _strip_json_fence(raw: str) -> str:
    s = (raw or "").strip()
    if s.startswith("```"):
        parts = s.split("```")
        if len(parts) >= 2:
            s = parts[1]
            if s.lstrip().startswith("json"):
                s = s.lstrip()[4:]
        s = s.strip()
    return s


def generate_code_project(
    user_prompt: str,
    stack_hint: str = "",
    continuation_note: str | None = None,
) -> tuple[dict[str, Any] | None, str | None]:
    """
    Returns a dict: project_name (str), summary (str), files (list of {path, content}).
    On truncated JSON / length stop, returns (None, "OUTPUT_TRUNCATED").
    """
    prompt = (user_prompt or "").strip()
    if not prompt:
        return None, "Describe what you want to build."
    if len(prompt) > 24000:
        return None, "Request is too long (max 24000 characters)."

    stack = (stack_hint or "").strip()[:120]
    client, err = _get_client()
    if err:
        return None, err

    extra = ""
    if continuation_note and continuation_note.strip():
        extra = f"\n\nAdditional instruction:\n{continuation_note.strip()[:4000]}"

    spec = f"""Build downloadable source files the user will open in the app, preview file-by-file, and download as one ZIP.

Full specification (constraints and features — respect all of it):
{prompt}

Tech / language hint (may be empty — pick a sensible stack if so): {stack or "auto"}
{extra}

Return a single JSON object with exactly these keys:
- "project_name": short slug, lowercase letters digits and hyphens only, max 40 characters
- "summary": one sentence describing what you generated
- "files": array of 1 to 14 objects, each with "path" (relative path, forward slashes, no ".." segments) and "content" (complete UTF-8 file body as a string)

Mandatory:
- The files array MUST NOT be empty. Every path MUST be a real relative path; every content MUST be the full file body (not an excerpt or placeholder-only).
- If the request is a project, app, website, API, or multi-part program: include at least 2 files (e.g. main module + README.md, or frontend + config).
- If the request is a single script or snippet only: one file is enough, with a clear path (e.g. main.py).

Rules:
- Prefer real, runnable code over placeholders like TODO unless unavoidable.
- Include README.md for any multi-file project so the user can run it after download.
- Text files only (source, config, markdown). No binary.
- Keep each file under 12000 characters; use fewer, focused files if needed.
- If output might be too long, prefer fewer files with complete content over many truncated files.
- Output ONLY the JSON object, no markdown fences."""

    messages = [
        {"role": "system", "content": CODE_PROJECT_SYSTEM},
        {"role": "user", "content": spec},
    ]

    last_err: Exception | None = None
    for model_name in _model_candidates():
        try:
            resp = client.chat.completions.create(
                model=model_name,
                messages=messages,
                temperature=0.35,
                max_completion_tokens=16384,
                top_p=1,
                stream=False,
                stop=None,
            )
            ch0 = resp.choices[0]
            raw = (ch0.message.content or "").strip()
            finish = getattr(ch0, "finish_reason", None)
            raw = _strip_json_fence(raw)
            try:
                data = json.loads(raw)
            except json.JSONDecodeError:
                logger.warning("Groq code project JSON parse failed finish=%s model=%r", finish, model_name)
                if finish == "length" or len(raw) > 100:
                    return None, "OUTPUT_TRUNCATED"
                return None, "Could not parse AI response. Try again."
            if not isinstance(data, dict):
                return None, "Invalid AI response format."
            pn = str(data.get("project_name", "")).strip()
            summary = str(data.get("summary", "")).strip()
            files = data.get("files")
            if not isinstance(files, list) or len(files) < 1:
                return None, "The model did not return usable files. Try again with more detail."
            out_files: list[dict[str, str]] = []
            for item in files:
                if not isinstance(item, dict):
                    continue
                path = str(item.get("path", "")).strip().lstrip("/")
                content = str(item.get("content", ""))
                if path and content is not None:
                    out_files.append({"path": path, "content": content})
            if len(out_files) < 1:
                return None, "No valid files in the AI response. Try again."
            return {
                "project_name": pn or "generated-project",
                "summary": summary[:500],
                "files": out_files,
            }, None
        except Exception as e:
            if _is_model_not_found(e):
                last_err = e
                logger.warning("Groq model %r unavailable (%s); trying fallback", model_name, e)
                continue
            logger.exception("Groq generate_code_project failed — model=%s error=%s", model_name, e)
            return None, _friendly_api_error(e)

    return None, _friendly_api_error(last_err) if last_err else "No Groq model available."


def generate_transcript_json(
    scenario: str,
    room_summary: str,
    num_turns: int,
) -> tuple[list[dict[str, str]] | None, str | None]:
    """Returns list of {"side": "me"|"other", "text": "..."} or error."""
    scenario = (scenario or "").strip()
    if not scenario:
        return None, "Describe what conversation you want."
    if len(scenario) > 4000:
        return None, "Scenario is too long."

    n = max(4, min(int(num_turns or 8), 24))

    client, err = _get_client()
    if err:
        return None, err

    ctx = (room_summary or "").strip()[:2000]
    prompt = f"""Create a fictional chat transcript for a messaging app.

Context about the chat (may be empty): {ctx}

User request: {scenario}

Return a JSON array of {n} messages alternating speakers. Each item must be an object with:
- "side": either "me" (the user who requested this) or "other" (the other participant)
- "text": the message text (natural, casual chat; each under 400 characters)

Start with "me" or "other" as appropriate. Output ONLY the JSON array, no markdown fences."""

    messages = [
        {"role": "system", "content": TRANSCRIPT_SYSTEM},
        {"role": "user", "content": prompt},
    ]

    last_err: Exception | None = None
    for model_name in _model_candidates():
        try:
            resp = client.chat.completions.create(
                model=model_name,
                messages=messages,
                temperature=1,
                max_completion_tokens=2048,
                top_p=1,
                stream=False,
                stop=None,
            )
            raw = (resp.choices[0].message.content or "").strip()

            # Strip markdown fences if model ignores instruction
            if raw.startswith("```"):
                raw = raw.split("```")[1]
                if raw.startswith("json"):
                    raw = raw[4:]
                raw = raw.strip()

            data = json.loads(raw)
            if not isinstance(data, list):
                return None, "Invalid AI response format."

            cleaned: list[dict[str, str]] = []
            for item in data:
                if not isinstance(item, dict):
                    continue
                side = str(item.get("side", "")).lower()
                t = str(item.get("text", "")).strip()
                if side not in ("me", "other") or not t:
                    continue
                cleaned.append({"side": side, "text": t[:2000]})

            if len(cleaned) < 2:
                return None, "Could not parse a usable transcript. Try again with a clearer prompt."
            return cleaned, None

        except json.JSONDecodeError:
            logger.warning("Groq transcript JSON parse failed for model %r", model_name)
            return None, "Could not parse AI response. Try again."
        except Exception as e:
            if _is_model_not_found(e):
                last_err = e
                logger.warning("Groq model %r unavailable (%s); trying fallback", model_name, e)
                continue
            logger.exception("Groq generate_transcript_json failed — model=%s error=%s", model_name, e)
            return None, _friendly_api_error(e)

    return None, _friendly_api_error(last_err) if last_err else "No Groq model available."


def summarize_recent_messages(lines: list[str]) -> tuple[str | None, str | None]:
    """Compact summary of last messages for context."""
    if not lines:
        return None, "No messages to summarize."

    client, err = _get_client()
    if err:
        return None, err

    blob = "\n".join(lines[-40:])[:12000]
    summary_prompt = (
        "Summarize this chat history in 3–6 short bullet points for the user. "
        "Focus on decisions, open questions, and tone.\n\n---\n" + blob
    )

    messages = [{"role": "user", "content": summary_prompt}]

    last_err: Exception | None = None
    for model_name in _model_candidates():
        try:
            resp = client.chat.completions.create(
                model=model_name,
                messages=messages,
                temperature=0.5,
                max_completion_tokens=512,
                top_p=1,
                stream=False,
                stop=None,
            )
            out = (resp.choices[0].message.content or "").strip()
            return (out, None) if out else (None, "Empty summary.")
        except Exception as e:
            if _is_model_not_found(e):
                last_err = e
                logger.warning("Groq model %r unavailable (%s); trying fallback", model_name, e)
                continue
            logger.exception("Groq summarize failed — model=%s error=%s", model_name, e)
            return None, _friendly_api_error(e)

    return None, _friendly_api_error(last_err) if last_err else "No Groq model available."


def _friendly_api_error(e: Exception) -> str:
    if e is None:
        return "AI request failed. Please try again."
    msg = str(e).lower()
    if "api key" in msg or "401" in msg or "invalid_api_key" in msg or "incorrect api key" in msg:
        return "Groq API key is invalid or missing. Check GROQ_API_KEY in your environment."
    if "403" in msg or "permission" in msg or "forbidden" in msg:
        return "Groq API key does not have permission. Check your Groq plan at console.groq.com."
    if "429" in msg or "rate_limit" in msg or "quota" in msg:
        return "Groq rate limit hit. Try again in a moment."
    if "404" in msg or "not found" in msg or "model_not_found" in msg or "decommissioned" in msg:
        return (
            "That Groq model is not available. "
            "Set GROQ_MODEL to llama-3.3-70b-versatile in your environment."
        )
    if "connection" in msg or "timeout" in msg:
        return "Could not connect to Groq API. Check your network and try again."
    return f"Groq request failed: {str(e)[:120]}"
